name: Daily News Summary

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-news-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

- name: Install dependencies
  run:
    pip install feedparser requests beautifulsoup4 schedule pytz twilio
    pip install openai==0.28  # fixa na versão compatível


      - name: Run news agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        run: |
          python3 news_agent.py
