name: Meal planner WhatsApp

on:
  schedule:
    # Executa às 11:00 UTC todo domingo, que corresponde a 08:00 em São Paulo (UTC−3)
    - cron: '0 11 * * SUN'
  # Permite acionar manualmente via interface do GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Credenciais e números definidos nos segredos do repositório
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
      WHATSAPP_RECIPIENT: ${{ secrets.WHATSAPP_RECIPIENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 schedule twilio

      - name: Run meal planner via WhatsApp
        run: python meal_planner_whatsapp.py
